name = "the-mind-game-online-3-0"
main = "worker/index.ts"
compatibility_date = "2026-03-07"

[[durable_objects.bindings]]
name = "LOBBY_SERVER"
class_name = "LobbyServer"

[[durable_objects.bindings]]
name = "LOBBY_REGISTRY"
class_name = "LobbyRegistry"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["LobbyServer"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["LobbyRegistry"]

[vars]
ALLOWED_ORIGINS = "https://the-mind-game-worker.lmarogna02.workers.dev,http://localhost:3000,https://themindgameonline3-0-pages.pages.dev/"